### ISSUE TITLE
OS/2 -> codePageRange

### ISSUE THREAD

**Issue by mLihs** [foliojs/fontkit#169]
hello does the values describe the position int font file wehre I can read the supported codePages of the font ? As I read both are init32 values
OS/2 -> codePageRange [value1 , value2 ]
can u help me on this topic please ?

**Comment by Pomax** [comment]
As per https://docs.microsoft.com/en-us/typography/opentype/spec/os2#cpr, these are two int32 values that don't represent two numbers, but represent 64 individual bits, each bit corresponding to a specific codepage.

**Comment by mLihs** [comment]
Thank,  I also found short after my post the page.
i made a code pen example and it seams to work. 

https://codepen.io/mlihs/pen/pZPwqR

HeitiTC: codePageRange: [ 1610744223, 3755409408 ]
Roboto : codePageRange: [ 536871327, 1325465600 ]
