### ISSUE TITLE
Include `fileName` as a meta property on the font.

### ISSUE THREAD

**Issue by roydukkey** [foliojs/fontkit#177]
It should be possible to get the filename of the font from within the callback of `fontkit.open()`.

**Comment by Pomax** [comment]
What would be an example of a situation where you've called fontkit.open() but you don't have access to the name of the file at the same time? (it's still just JS so if you really need this: just tack it on, nothing stops you from saying `font._filename = filenameVarIwasUsing`)

**Comment by roydukkey** [comment]
How would it be possible to provide the proper filename to the callback of `font.open()`? This this is an async function, I'm not sure of a way to easily handle this outside of the scope of the callback function. Since then, my thinking led me to believe that it would be easiest to provide it on the `font` parameter of the callback function.

```
const fontList = [
	'./fonts/my-font-italic-400.ttf',
	'./fonts/my-font-italic-600.ttf',
	'./fonts/my-font-normal-400.ttf',
	'./fonts/my-font-normal-600.ttf'
];

let subsetGlyphs = 'Hi ya!';

for (const fontFile of fontList) {
	fontkit.open(fontFile, (err, font) => {
		const run = font.layout(subsegGlyphs);
		const subset = font.createSubset();

		run.glyphs.forEach(function(glyph) {
			subset.includeGlyph(glyph);
		});

		let filename = font.fileName;
		filename = path.join(path.dirname(filename), path.basename(filename, path.extname(filename)) + '.subset' + path.extname(filename));
 
		subset.encodeStream()
			.pipe(fs.createWriteStream('subset.ttf', (err) => {
				if (err) throw err;
				console.log(`[fontkit] Generated '${filename}'.`);
			}));
	});
}
```
*^^ This code proably doesn't work. Do not copy.*

**Comment by Pomax** [comment]
You can fairly easily do something like this:
```
for (const filename of fontList) {
    fontkit.open(filename, (err, font) => {
        font._filename = filename;
        // ...
    });
}
```
and then do anything you want: you already have the filename because you can't open a file without it, and JS scoping rules keeps the value around for binding in the callback.

**Comment by roydukkey** [comment]
Okay. I see your point. I think I'll dealing with a design issue in my project them. Thanks.
