### ISSUE TITLE
Broken test GVAR-9

### ISSUE THREAD

**Issue by brawer** [foliojs/fontkit#182]
![image](https://user-images.githubusercontent.com/1527880/48248148-75a4e180-e3f6-11e8-8ca0-a52be16ec7c4.png)

https://rawgit.com/unicode-org/text-rendering-tests/master/reports/fontkit.html#GVAR-9

See also: https://unicode.org/mailman/private/opentype-layout/2018-November

**Comment by Connum** [comment]
While implementing variable font rendering in Opentype.js and looking at at fontkit's implementation, I encountered this issue as well and found a fix for it. This should also fix other strange effects that could happen when slowly changing the axis coordinates.
