### ISSUE TITLE
'ff' ligature in Source Han renders wierdly

### ISSUE THREAD

**Issue by casperno** [foliojs/fontkit#197]
When rendering 'ff' in Source Han Sans, the ligature looks very strange. 
Reproducible on https://fontkit-demo.now.sh/

Same font with ligature looks ok in Indesign, but give the nature of CJK fonts, I'm not sure that it's a direct comparison.

[SourceHanSansCN_Normal.otf.zip](https://github.com/foliojs/fontkit/files/2965778/SourceHanSansCN_Normal.otf.zip)

**Comment by Pomax** [comment]
Source HAN Sans, Source HAN serif, or both?

**Comment by casperno** [comment]
Source Han Sans regular

Sendt fra min iPhone

14. mar. 2019 kl. 16:40 skrev Pomax <notifications@github.com>:

Source HAN Sans, Source HAN serif, or both?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/foliojs/fontkit/issues/197#issuecomment-472925055>, or mute
the thread

**Comment by casperno** [comment]
<img width="607" alt="Skjermbilde 2019-03-14 kl  21 21 58" src="https://user-images.githubusercontent.com/3234493/54389287-03902200-46a0-11e9-82d1-12fbe85f9a56.png">

This is what I get using SourcHanSansCN_normal

**Comment by Pomax** [comment]
Your attached font indeed looks broken, but using the official releases I can't reproduce this, and if I use a tool like Font Creator to subset your font to only have the latin block (with ligatures) things look fine again, so it feels like wherever you got your copy of the font did _something_ to it that subtly breaks it.

**Comment by casperno** [comment]
Thank you so much for looking into this. The font came from a client — replacing it with the official version does seem to be the best choice. Or disable ligatures.
