### ISSUE TITLE
[Request]: add typoAscender and typoDescender metrics

### ISSUE THREAD

**Issue by simonwilbert** [foliojs/fontkit#198]
Some apps use the typoAscender and typoDescender values of a font to determine the offset of the first baseline in a text box and the minimum size of a text box below which the display of type is suppressed.

Please could fontKit be updated to include these additional two metrics?

**Comment by moyogo** [comment]
These are already by accessible via `font['OS/2'].typoAscender`, `font['OS/2'].typoDescender` and `font['OS/2'].typoLineGap` when the OS/2 table is present. Do you mean you want them as `font.typoAscender`, `font.typoDescender` and `font.typoLineGap`?

**Comment by simonwilbert** [comment]
Thanks for this information.
