### ISSUE TITLE
Extracting Glyph path for CJK fonts with Italic or bold 

### ISSUE THREAD

**Issue by ningliu19** [foliojs/fontkit#217]
Hi, I'm trying to use fontkit to extract glyph path from CJK fonts, regular style is OK, but I'm not able to get Italic or bold styled glyph path from CJK fonts. Wondering if this is supported by fontkit?
Thanks!

**Comment by devongovett** [comment]
Italic and bold variants are usually in separate font files.

**Comment by ningliu19** [comment]
@devongovett thanks for replying! I want to detail a bit:
for example, I want to fetch a Chinese character in Arial font, the glyph is:
![image](https://user-images.githubusercontent.com/50339619/74894609-7fd5bf80-535d-11ea-8c37-31cc58a9489c.png)
Obviously, `id` is 0 and the glyph path is a 10 segment array(which looks like a box). So does this mean this font cannot be loaded by fontkit? 
thanks!

**Comment by Pomax** [comment]
the id being 0 means the glyph does not exist in this font and you got the `.notdef` identifier back.

**Comment by ningliu19** [comment]
@Pomax ah..ok, thanks!

**Comment by ningliu19** [comment]
@Pomax however, I tried a font `PingFang SC`, still it returns `.notdef`. I'm very sure this font has the glyph, and in Mac osX `pages` it looks like this:
![image](https://user-images.githubusercontent.com/50339619/74940461-73824e80-53bf-11ea-9be7-9f1ada3189f7.png)

**Comment by ningliu19** [comment]
![image](https://user-images.githubusercontent.com/50339619/74941882-cceb7d00-53c1-11ea-841c-9a51693288ff.png)
I also noticed the `hasError` is true for the returned glyph.

**Comment by Pomax** [comment]
Yep, that sure looks like an error in the CFF parsing part of Fontkit.

**Comment by devongovett** [comment]
Probably fixed by #224?
