### ISSUE TITLE
Release 1.9.0

### ISSUE THREAD

**Issue by Pomax** [foliojs/fontkit#218]
The current codebase is from November 2019, the last release was 1.8.0 from March 2019 - can a new version be tagged and pushed out @devongovett? There are a number of fixes that are worth getting out into the world =)

**Comment by edwardsph** [comment]
+1 as PDFKit needs this update. Fontkit 1.8.0 is pulling in an old version of acorn (via brfs) which has a Regex DoS vulnerability. The current codebase already resolves this by updating brfs.

**Comment by Pomax** [comment]
bump @devongovett

**Comment by RoelN** [comment]
+1

**Comment by devongovett** [comment]
Published 1.8.1 today.
