### ISSUE TITLE
Dependency on 3-years-old babel-runtime

### ISSUE THREAD

**Issue by fjf2002** [foliojs/fontkit#219]
Your project has a dependency on 3-years-old babel-runtime. Please upgrade, probably to @babel/runtime ?

**Comment by blikblum** [comment]
https://github.com/foliojs/fontkit/pull/196 updates the dependencies, removing dependency on babel-runtime

**Comment by Tilogorn** [comment]
Unfortunately didn't make it to the latest release. @devongovett Do you mind merging this PR https://github.com/foliojs/fontkit/pull/196 (as you tagged the last release) and release it? As others said (https://github.com/foliojs/fontkit/issues/204) the terminal gets spammed by core-js. Plus the core-js maintainer is arrested in jail, the state of the project is very unclear.

**Comment by valentijnscholten** [comment]
``
warning pdfmake > pdfkit > fontkit > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
``

**Comment by MrSnix** [comment]
@devongovett Do you mind merging this PR #196? Thanks a lot.

**Comment by fjf2002** [comment]
Now I use @foliojs-fork/pdfkit / @foliojs-fork/fontkit.
