### ISSUE TITLE
Convert path.toSVG() output back to original text?

### ISSUE THREAD

**Issue by rickybrown** [foliojs/fontkit#245]
Hopefully I'm not overlooking something that's already been addressed, but given this scenario, what could i do in the second function to get the original character codes/original string from svg info?: 

```javascript
const fontkit = require('fontkit');
const font = fontkit.openSync(__dirname + '/font.ttf');

// Works great
const StringToSVG = string => {
  let run = font.layout(string)

  return run.glyphs.map(g => g.path.toSVG())
}

let svg = StringToSVG(string)


const SVGtoString = svg => {
  // What can i do with these SVG Paths?
}

let originalString = SVGtoString(svg)

// To get this output?
console.log(originalString)
```

**Comment by Pomax** [comment]
You can't? Once you turn the text into outline vector graphics, you lose any relation to the original text. Unless you want to perform OCR of course. Instead, make your code remember which SVG belongs to which text and don't try to convert svg to text, but directly look up with text belongs to which svg path.
