### ISSUE TITLE
Pls update dependencies

### ISSUE THREAD

**Issue by corran2go** [foliojs/fontkit#250]
Hi,

as this lib is used in "pdfmake" which I love and use in my projects, it would be nice to update the babel dependencies.
The used "babel-runtime@6" requires "core-js@2" which is no longer maintained and not recommended for usage.

**Comment by kelly-tock** [comment]
yes please!!!!

**Comment by Pomax** [comment]
alternatively, given what this lib does, switching to esbuild probably makes even more sense.
