### ISSUE TITLE
How to load font in browser?

### ISSUE THREAD

**Issue by defpis** [foliojs/fontkit#256]
Is there some apis like opentype.js `opentype.load('font.ttf')` to load font by http

**Comment by Pomax** [comment]
see if https://github.com/foliojs/fontkit/issues/77#issuecomment-356916652 works for you, although [opentype.js](https://github.com/opentypejs/opentype.js) (for glyph work) or [lib-font.js](https://github.com/Pomax/lib-font) (for non-glyph work) might be better supported candidates. No one's really working on fontkit atm, unfortunately.

**Comment by defpis** [comment]
Thanks
