### ISSUE TITLE
COLRv1 Support

### ISSUE THREAD

**Issue by jlarmstrongiv** [foliojs/fontkit#270]
The COLRv1 is on the horizon, with gradients, compositing, blending, and more.  Currently, fontkit supports [COLRv0](https://github.com/foliojs/fontkit/blob/master/src/glyph/COLRGlyph.js)

- the spec 
  - https://docs.microsoft.com/en-us/typography/opentype/spec/colr#colr-formats
  - https://github.com/googlefonts/colr-gradients-spec/
- chrome 
  - https://chromestatus.com/feature/5638148514119680
  - https://developer.chrome.com/blog/colrv1-fonts/
  - https://blog.chromium.org/2022/01/chrome-98-beta-color-gradient-vector.html
- caniuse https://github.com/Fyrd/caniuse/issues/6097
- examples 
  - https://github.com/googlefonts/color-fonts
  - https://github.com/rsheeter/Bungee/blob/main/README.md#build-your-own-copy
- related
  - the example on https://github.com/foliojs/fontkit/issues/260#issuecomment-894583312
  - this issue https://github.com/foliojs/fontkit/issues/211#issuecomment-948603970

**Comment by Pomax** [comment]
Note that the real spec is https://docs.microsoft.com/en-us/typography/opentype/spec/colr#colr-formats, though.

**Comment by jlarmstrongiv** [comment]
Great find @Pomax!  

I haven’t worked much with parsers, but I think your [svg example](https://github.com/foliojs/fontkit/issues/260#issuecomment-893610741) and [restructure](https://github.com/foliojs/restructure/tree/v0.5.4) is interesting.  

I can extract and post my existing COLRv0 code and then explore how to add support for the new features.

**Comment by Pomax** [comment]
In terms of the parser: we can probably hack something into existence, similar to what we did with the SVG parser, as COLRv1 isn't terribly complex, just "a lot more (linked) simple structures". The tricky bit will be in turning them into something you can actually see.

**Comment by jlarmstrongiv** [comment]
@Pomax it certainly sounds possible.  If you’re able to hack together the parser, then I will be able to format and massage the data into a usable svg.  I think it’d be useful to other people in the future too 😄

**Comment by Pomax** [comment]
stubbing something out over on https://github.com/Pomax/fontkit-colrv1, but it's a _lot_ of small bits of code, so no promises on when I might finish (if ever, because "yet another repo" is exactly what my overloaded schedule needed ;)

**Comment by jlarmstrongiv** [comment]
Thank you @Pomax !  That’s a great start.  What’s the best way to contact you?

**Comment by Pomax** [comment]
Email's best, although I may be slow to respond (I think you already emailed me) because things have gotten a bit crazy and I'm currently balancing "having to use a keyboard" with "not actually being able to use a keyboard due to an injury" >_>

**Comment by jlarmstrongiv** [comment]
Ouch!  Hope you make a full recovery @Pomax.  I remember a few tips for hands-free coding from https://www.joshwcomeau.com/blog/hands-free-coding/  Feel free to followup in a few weeks or a few months, whenever you feel better with schedule permitting.

**Comment by Lorp** [comment]
This is @simoncozens’ PR for COLRv1 support: #298

**Comment by jlarmstrongiv** [comment]
Closing in favor of #298
