### ISSUE TITLE
There are security vulnerabilities in many child dependancies

### ISSUE THREAD

**Issue by AbhaySBhosale** [foliojs/fontkit#271]
Many of child dependancies have the vulnerabilities, We did scan with blackduck and found below libraries have vulnerabilities

browserify,  brfs, brotli etc
font-kit version: 1.8.0

**Comment by devongovett** [comment]
It's on my list to modernize the build system, but I've been quite busy lately. Would you like to send a PR to remove the browserify related deps (`brfs`, `browserify-optional`) and config options in the package.json? I think we can safely drop that at this point.

**Comment by fjf2002** [comment]
Use @foliojs-fork/pdfkit / @foliojs-fork/fontkit
