### ISSUE TITLE
babel-runtime ^6.26.0 is outdated

### ISSUE THREAD

**Issue by zdm** [foliojs/fontkit#273]
Hi,
`babel-runtime@"^6.26.0"` is outfated and contains vulnerable deps.
Seems, that this module is not maintained anymore, last update was 2 years ago.
Could you please use pure pabel core module?

**Comment by zdm** [comment]
Or use more modern version `^7`.

**Comment by zdm** [comment]
Please, update this dependency, it breaks build with webpack.
This is a problem.

**Comment by zdm** [comment]
And needt to move babel deps to the `devDependencies`, because they are not used in production.

**Comment by zdm** [comment]
Are you alive?

**Comment by liborm85** [comment]
You can use fork https://github.com/foliojs-fork/fontkit with updated dependencies and other improvements.

**Comment by zdm** [comment]
Impossible, becauase fontkit is used by pdfkit, that is used by 
third-party dependency of my project.

**Comment by liborm85** [comment]
For pdfkit exists fork https://github.com/foliojs-fork/pdfkit too. But usage with other third-party dependency is problematic.
