### ISSUE TITLE
Newest version of restructure doesn't support all string encodings

### ISSUE THREAD

**Issue by timmyL17** [foliojs/fontkit#331]
It appears that the newest version of `restructure` does not support all string encodings. When I tried to open a font file on my mac, the font name fields were all null because `restructure` does not support the `x-mac-roman` encoding. Perhaps fontkit should depend strictly on `restructure` v3.0.0 until `restructure` updates?

https://github.com/foliojs/restructure/issues/60#issue-2224034510

**Comment by srl295** [comment]
@timmyL17 can you give a reproducer?

**Comment by srl295** [comment]
@timmyL17 or at least a reproducing font? wasn't able to repro with the font mentioned in the linked ticket:

```js
var fontkit = require('fontkit');

// open a font synchronously
var font = fontkit.openSync('src/arial-bold.ttf');

// layout a string, using default shaping features.
// returns a GlyphRun, describing glyphs and positions.
var run = font.layout('hello world!');

// get an SVG path for a glyph
var svg = run.glyphs[0].path.toSVG();

// create a font subset
var subset = font.createSubset();
run.glyphs.forEach(function(glyph) {
  subset.includeGlyph(glyph);
});

let buffer = subset.encode();
console.dir({buffer});
```

**Comment by srl295** [comment]
also repro:
- clone fontkit
- `npm i`
- `npm t` (passes)
- `npm i --save restructure@3.0.1`
- `npm t` (fails)

**Comment by srl295** [comment]
Here https://github.com/foliojs/fontkit/blob/master/src/tables/name.js

Is where random encodings are passed to restructure.

**Comment by timmyL17** [comment]
Thanks, you beat me to it. That was essentially my repro. I should have posted it at the beginning.
