### ISSUE TITLE
Unused dependancy: brfs

### ISSUE THREAD

**Issue by simon-paris** [foliojs/fontkit#45]
Brfs is a very large module. Could it be moved to devDependancies if possible?

**Comment by devongovett** [comment]
The problem is that it's required for browserify builds. Moving it to devDependencies would require the user to know to install brfs along with fontkit, or whatever required fontkit.

**Comment by jahewson** [comment]
Perhaps it could be moved to`peerDependencies`? That way npm will print a message.

**Comment by Pomax** [comment]
if it's in devdependencies it will still get installed, unless the user explicitly runs `npm install --production`

**Comment by devongovett** [comment]
@Pomax only if you are running `npm install` in the fontkit folder. If you are installing something that has fontkit as a dependency (e.g. `npm install pdfkit`), devDependencies won't be installed.

**Comment by Pomax** [comment]
ah, right.

**Comment by devongovett** [comment]
For [brotli.js](https://github.com/devongovett/brotli.js) I managed to get rid of brfs by writing a base64 JS string version of the binary file and using `require` instead of `fs.readFileSync`. e.g. `module.exports="base64";`. Maybe we can do something similar here. Currently the only file we need to read is the Unicode trie for the arabic shaper.

**Comment by awerlang** [comment]
Currently, not only `brfs` but also `browserify-optional`, from this module and also in `restructure`, `unicode-properties`. It would chop away 40% of node_modules.

**Comment by mclark-newvistas** [comment]
It would also help fix the `npm audit` warnings about security vulnerabilities for `PDFMake`. See also [bpampuch/pdfmake#1639](https://github.com/bpampuch/pdfmake/issues/1639).

**Comment by RoelN** [comment]
All this talk about chopping off large chunks of depedencies makes me happy. It'd speed up [Wakamai Fondue](https://wakamaifondue.com) considerably. E.g. I'd only need Brotli to decompress fonts, not to compress them.

**Comment by devongovett** [comment]
Unfortunately, all of those dependencies are still required. They are used for builds using browserify.

**Comment by Pomax** [comment]
@RoelN what part would it speed up, though? The runtime should not be noticably affected by the dependency.

**Comment by gbayliss** [comment]
Hving real touble with this, npm install pdfkit --only=prod is kicking this back as a vulnerbility.  From what I understand this shouldn't even be installed.  Am I doing something wrong?  Same issue on linebreak too.

**Comment by gbayliss** [comment]
> @Pomax only if you are running `npm install` in the fontkit folder. If you are installing something that has fontkit as a dependency (e.g. `npm install pdfkit`), devDependencies won't be installed.

@devongovett  I'm not convinced by this statement.  I believe it depends entirely upon the value of NODE_ENV.  Please see my previous comment

**Comment by awerlang** [comment]
@gbayliss https://docs.npmjs.com/cli/install

**Comment by gbayliss** [comment]
@awerlang thanks, I read that and tried several permutations but I am still seeing this included when installing the downstream package (pdfkit).  As I want to run this using nodejs on Google Cloud functions, there's no need for browser builds.  Unfortunately my understanding of the side-builds for these projects is limited but it appears that the inclusion of browserify results in some undesirable consequences for node users.  It looks like there are complications in attempting to resolve the matter.

**Comment by RoelN** [comment]
@Pomax I meant in package size, reducing download time. I don't expect any real difference in runtime.
