### ISSUE TITLE
Bundling with webpack does not work

### ISSUE THREAD

**Issue by schneck** [foliojs/fontkit#67]
Hi,

running fontkit (and pdfkit) in an expressjs app works fine locally, but when I'm building it with webpack, it returns: `Error: ENOENT: no such file or directory, open '/var/www/backend/data.trie'`

This is my webpack config:

```
var Webpack = require('webpack');
var path = require('path');
var buildPath = path.resolve(__dirname, 'build');
var mainPath = path.resolve(__dirname, 'src', 'app.js');

var config = {

  target: 'node',
  entry: mainPath,
  output: {
    path: buildPath,
    filename: 'bundle.js'
  },
  node: {
    console: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    dns: 'empty',
    __dirname: false,
    __filename: false
  },
  module: {
    loaders: [
        {
            test: /\.js$/,
            loader: 'babel',
            query: {
                presets: ['es2015']
            }
        },
        {
            test: /\.json$/,
            loader: 'json'
        },
        ]
  }
};

module.exports = config;
```

When I copy the file `data.trie` from the `node_modules` folder to the same directory where I run the node app, it continues, but the same problem appears with `use.trie` then. 
Any idea how to solve it?

**Comment by joseSantacruz** [comment]
I have the same issue any help

**Comment by Pomax** [comment]
Is there a trace available that explains where that error is thrown?

**Comment by liborm85** [comment]
In pdfmake we using brfs transformation ( see https://github.com/bpampuch/pdfmake/blob/33df9bbec76b358bec8d08bc49a1d2892445a3fa/webpack.config.js#L63 ). And then no external files are required.

**Comment by daveross** [comment]
@Pomax Here's a stack trace:

```
dave@DMR-SURFACEPRO3:/mnt/c/Users/dave/Code/font-server$ node app/dist/bundle.js
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '//data.trie'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.<anonymous> (/mnt/c/Users/dave/Code/font-server/app/dist/bundle.js:41204:27)
    at Object.module.exports.categories (/mnt/c/Users/dave/Code/font-server/app/dist/bundle.js:41338:30)
    at __webpack_require__ (/mnt/c/Users/dave/Code/font-server/app/dist/bundle.js:20:30)
    at Object.<anonymous> (/mnt/c/Users/dave/Code/font-server/app/dist/bundle.js:21372:31)
    at Object.<anonymous> (/mnt/c/Users/dave/Code/font-server/app/dist/bundle.js:36269:30)
    at __webpack_require__ (/mnt/c/Users/dave/Code/font-server/app/dist/bundle.js:20:30)
    at Object.<anonymous> (/mnt/c/Users/dave/Code/font-server/app/dist/bundle.js:9158:17)
    at __webpack_require__ (/mnt/c/Users/dave/Code/font-server/app/dist/bundle.js:20:30)
```

**Comment by albertodotcom** [comment]
I got it working by installing `transform-loader` -> `npm i transform-loader --save-dev`

and then in the `webpack.config.js`
```js
    module: {
        loaders: [
            ...loaders,
            {enforce: 'post', test: /fontkit[\/\\]index.js$/, loader: "transform?brfs"},
	    {enforce: 'post', test: /unicode-properties[\/\\]index.js$/, loader: "transform?brfs"},
            {enforce: 'post', test: /linebreak[\/\\]src[\/\\]linebreaker.js/, loader: "transform?brfs"}
        ]
    },
```

I hope this helps.

**Comment by kendrickkesley** [comment]
Hello, I got fs is undefined when using transform-loader?brfs in fontkit. How do you guys resolve this issue?

**Comment by Pomax** [comment]
Looking at https://github.com/webpack-contrib/transform-loader#webpack-2-config-example, it feels like the confs shown so far are not quite in line with how `brfs` should be used with webpack. It might be worth replicating the code as shown in the transform-loader README.md and seeing if that solves the problem.

**Comment by Tinoooo** [comment]
@albertoforni suggestion helps.
For newer webpack versions, this works for me:
```
module: {
        rules: [
            {enforce: 'post', test: /unicode-properties[\/\\]index.js$/, loader: "transform-loader?brfs"},
            {enforce: 'post', test: /fontkit[\/\\]index.js$/, loader: "transform-loader?brfs"},
            {enforce: 'post', test: /linebreak[\/\\]src[\/\\]linebreaker.js/, loader: "transform-loader?brfs"}
        ]
    }
```

Are there any plans to implement a solution, that works without these workarounds?

**Comment by hyvyys** [comment]
I don't want to mess with my conf just to get this to work in the browser, this should work out of the box.

**Comment by hyvyys** [comment]
Any idea how to modify the webpack config via chainWebpack? (I'm trying to use fontkit in a Vue app that uses Vue-CLI).

**Comment by blikblum** [comment]
Try fontkit-next package. It has this [PR](https://github.com/foliojs/fontkit/pull/208) applied and should work

**Comment by bjbk** [comment]
I still can't seem to get pdfkit to bundle properly either.  Runs in dev mode but not in a build.  (Electron 10.1.3)
The console is giving me the `ENOENT, data.trie not found` error.
Quasar app (Vue) and added this to my `quasar.conf.js` file after installing `transform-loader` as a dev dependency.
```
extendWebpack (cfg) {
  cfg.module.rules.push(
    { enforce: 'post', test: /unicode-properties[/\\]index.js$/, loader: 'transform-loader?brfs' },
    { enforce: 'post', test: /fontkit[/\\]index.js$/, loader: 'transform-loader?brfs' },
    { enforce: 'post', test: /linebreak[/\\]src[/\\]linebreaker.js/, loader: 'transform-loader?brfs' }
  )
}
```
I may have misunderstood how the `quasar.conf.js` works when extending Webpack.  https://quasar.dev/quasar-cli/handling-webpack#Installing-loaders

All of this just so I can add fillable fields to a pdf generated in my Electron app.  (Electron itself makes pdf's from webviews without a library, but I have need for interactive PDF's.  Therefore, I had to build them all from scratch in a js file using fontkit adding the `formText()` methods only to have the production app crash. *sigh* )

Thanks to everyone here who has worked on this project.  The addition of Acroforms is what brought me here.  I'm certain I am mistaken in my implementation, but I have searched high and low for a solution.

**Comment by howlettga** [comment]
I don't think this is an adequate solution. `transform-loader` has not been updated for 4 years and doesn't purport to support greater than webpack 2.x. I am using webpack 5.x and would love to be able to handle this module with asset modules at the most and no crazy work-arounds. It would be really nice if fontkit handled importing these `.trie` files using standard import or require statements instead of reading directly off the filesystem. Is there any reason why it can't do this? I will take a look when I have some time to investigate

**Comment by Pomax** [comment]
at the very least, I'd say "see if it works with esbuild instead" given the monster that webpack is these days, and given how much faster (and arguably better) esbuild is.

That said, the way fontkit works it's entirely likely that still won't get you to something that works without running the .trie data build yourself as an explicit step in your build.

**Comment by michaeljherrmann** [comment]
The following worked for me:
```
const nodeExternals = require('webpack-node-externals');

config = {
    ...
    target: 'node',
    externals: [nodeExternals()],
    ...
};
```

As described by [webpack-node-externals:](https://www.npmjs.com/package/webpack-node-externals)
> When bundling with Webpack for the backend - you usually don't want to bundle its node_modules dependencies

That library is helpful to handle all `node_modules`, but you can also just specify `fontkit` in [externals](https://webpack.js.org/configuration/externals/)
```
config.externals = {
    'fontkit-next': 'commonjs fontkit-next',
};
```
